// Code generated by "stringer -type=BtnState"; DO NOT EDIT.

package streamdeck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BtnPressed-0]
	_ = x[BtnReleased-1]
	_ = x[BtnLongPressed-2]
}

const _BtnState_name = "BtnPressedBtnReleasedBtnLongPressed"

var _BtnState_index = [...]uint8{0, 10, 21, 35}

func (i BtnState) String() string {
	if i < 0 || i >= BtnState(len(_BtnState_index)-1) {
		return "BtnState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BtnState_name[_BtnState_index[i]:_BtnState_index[i+1]]
}
