// Code generated by "stringer -type=BtnState"; DO NOT EDIT.

package StreamDeck

import "strconv"

const _BtnState_name = "BtnPressedBtnReleased"

var _BtnState_index = [...]uint8{0, 10, 21}

func (i BtnState) String() string {
	if i < 0 || i >= BtnState(len(_BtnState_index)-1) {
		return "BtnState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BtnState_name[_BtnState_index[i]:_BtnState_index[i+1]]
}
